// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUmwduxlVJgrPVLlMr0Zu4xdWMBn6v_ro',
    appId: '1:1062948093927:web:842271a12c6b8a52b74742',
    messagingSenderId: '1062948093927',
    projectId: 'trusthire-fa302',
    authDomain: 'trusthire-fa302.firebaseapp.com',
    storageBucket: 'trusthire-fa302.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBr28rsY942dhhsiohZ0gsmPJHaOZUGk7c',
    appId: '1:1062948093927:ios:f80345dd44c841a7b74742',
    messagingSenderId: '1062948093927',
    projectId: 'trusthire-fa302',
    storageBucket: 'trusthire-fa302.firebasestorage.app',
    iosBundleId: 'com.example.trusthire',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBr28rsY942dhhsiohZ0gsmPJHaOZUGk7c',
    appId: '1:1062948093927:ios:f80345dd44c841a7b74742',
    messagingSenderId: '1062948093927',
    projectId: 'trusthire-fa302',
    storageBucket: 'trusthire-fa302.firebasestorage.app',
    iosBundleId: 'com.example.trusthire',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUmwduxlVJgrPVLlMr0Zu4xdWMBn6v_ro',
    appId: '1:1062948093927:web:8b760b265647292db74742',
    messagingSenderId: '1062948093927',
    projectId: 'trusthire-fa302',
    authDomain: 'trusthire-fa302.firebaseapp.com',
    storageBucket: 'trusthire-fa302.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmAA60GMkZY3sJd2vIV04qBBFBifQn-sA',
    appId: '1:1062948093927:android:359210b9ea477adfb74742',
    messagingSenderId: '1062948093927',
    projectId: 'trusthire-fa302',
    storageBucket: 'trusthire-fa302.firebasestorage.app',
  );
}
